name: Build [Android]

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false && (github.event_name == 'workflow_dispatch' || !contains(github.event.head_commit.message, 'noci')) }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: cachix/install-nix-action@v27
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: nicknovitski/nix-develop@v1

    - name: Build debug APK
      run: ./gradlew androidApp:packageDebug
    - name: Build release APK
      run: ./gradlew androidApp:packageRelease

    - name: Upload universal debug APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: spmp-android-debug
        path: androidApp/build/outputs/apk/debug/*.apk

    - name: Upload universal release APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: spmp-android-release
        path: androidApp/build/outputs/apk/release/*.apk
